# Generated by Django 4.2.13 on 2026-05-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('commune', 'Commune'), ('daira', 'Daïra'), ('wilaya', 'Wilaya'), ('ministere', 'Ministère'), ('prive', 'Privé'), ('etranger', 'Étranger')], max_length=50)),
                ('contact_nom', models.CharField(max_length=150)),
                ('contact_tel', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('intitule', models.CharField(max_length=500)),
                ('intitule_arabe', models.CharField(blank=True, max_length=500)),
                ('reference_marche', models.CharField(max_length=100, unique=True)),
                ('type_travaux', models.CharField(choices=[('batiment', 'Bâtiment'), ('tp', 'Travaux Publics'), ('hydraulique', 'Hydraulique'), ('vrd', 'VRD'), ('renovation', 'Rénovation'), ('amenagement', 'Aménagement')], max_length=50)),
                ('commune_chantier', models.CharField(max_length=100)),
                ('adresse_chantier', models.TextField(blank=True)),
                ('montant_marche_ht_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_tva', models.DecimalField(choices=[(9.0, '9%'), (19.0, '19%')], decimal_places=2, default=19.0, max_digits=4)),
                ('montant_marche_ttc_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_ordre_service', models.DateField()),
                ('delai_execution_jours', models.PositiveIntegerField()),
                ('date_fin_contractuelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle_prevue', models.DateField(blank=True, null=True)),
                ('avancement_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('budget_previsionnel_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('etude', 'Étude'), ('preparation', 'Préparation'), ('en_cours', 'En cours'), ('arret', "À l'arrêt"), ('reception_provisoire', 'Réception provisoire'), ('reception_definitive', 'Réception définitive'), ('clos', 'Clos'), ('litige', 'En litige'), ('resilie', 'Résilié')], default='etude', max_length=50)),
                ('taux_penalite_retard', models.DecimalField(decimal_places=4, default=0.0003, max_digits=5)),
                ('garantie_bonne_fin_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wilaya_chantier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='SituationTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('montant_cumul_ht_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_periode_ht_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avance_demarrage_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retenue_garantie_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_a_facturer_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tva_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_ttc_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='RentabiliteProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_realise_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_mo_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_materiaux_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_engins_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_sous_traitance_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frais_generaux_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge_brute_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge_brute_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('marge_nette_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge_nette_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('retard_jours', models.IntegerField(default=0)),
                ('penalites_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('derniere_maj', models.DateTimeField(auto_now=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rentabilite', to='projects.projet')),
            ],
        ),
    ]
