# Generated by Django 4.2.13 on 2026-05-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employe_projet_affecte_employe_user'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projets_chef', to='employees.employe'),
        ),
        migrations.AddField(
            model_name='projet',
            name='conducteur_travaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='employees.employe'),
        ),
    ]
