# Generated by Django 4.2.13 on 2026-05-02 10:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projet_chef_projet_projet_conducteur_travaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='taux_penalite_retard',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0003'), max_digits=5),
        ),
    ]
