# Generated by Django 4.2.13 on 2026-05-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(choices=[('CPA', 'CPA'), ('BEA', 'BEA'), ('BNA', 'BNA'), ('BADR', 'BADR'), ('BDL', 'BDL'), ('Societe_Generale_DZ', 'Société Générale Algérie'), ('CCP_Algerie_Poste', 'CCP Algérie Poste')], max_length=50)),
                ('intitule', models.CharField(max_length=200)),
                ('numero_compte', encrypted_model_fields.fields.EncryptedCharField()),
                ('rib', encrypted_model_fields.fields.EncryptedCharField()),
                ('solde_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devise', models.CharField(default='DZD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('classe', models.PositiveIntegerField()),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit'), ('mixte', 'Mixte')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_ecriture', models.DateField()),
                ('libelle', models.CharField(max_length=300)),
                ('montant_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='finance/pieces/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validée'), ('lettree', 'Lettrée')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte_credit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credits', to='finance.comptecomptable')),
                ('compte_debit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='debits', to='finance.comptecomptable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_valeur', models.DateField()),
                ('libelle', models.CharField(max_length=300)),
                ('montant_debit_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_credit_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_apres_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_operation', models.CharField(blank=True, max_length=100)),
                ('rapproche', models.BooleanField(default=False)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='finance.comptebancaire')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.ecriturecomptable')),
            ],
        ),
    ]
