# Generated by Django 4.2.13 on 2026-05-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField()),
                ('montant_ht_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=4)),
                ('montant_tva_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_ttc_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conditions_paiement', models.TextField()),
                ('lieu_livraison', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('confirme', 'Confirmé'), ('livre_partiel', 'Livré Partiel'), ('livre_total', 'Livré Total'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='achats/bons_commande/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_approuves', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_reception', models.DateField()),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non Conforme'), ('partiel', 'Partiel')], max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_reception', to='suppliers.boncommande')),
                ('receptionnaire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('objet', models.TextField()),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
                ('montant_estime_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('urgence', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('tres_urgente', 'Très Urgente')], default='normale', max_length=20)),
                ('justification', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('transformee', 'Transformée')], default='brouillon', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='demandes_achat', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='DomaineActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('reference_article', models.CharField(blank=True, max_length=100)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
                ('prix_unitaire_ht_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_ht_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='suppliers.boncommande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantite_recue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantite_conforme', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observation', models.CharField(blank=True, max_length=255)),
                ('bon_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='suppliers.bonreception')),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.ligneboncommande')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('raison_sociale', models.CharField(max_length=300)),
                ('forme_juridique', models.CharField(choices=[('SARL', 'SARL'), ('SPA', 'SPA'), ('EURL', 'EURL'), ('SNC', 'SNC'), ('EI', 'EI'), ('Cooperative', 'Coopérative')], max_length=20)),
                ('registre_commerce', encrypted_model_fields.fields.EncryptedCharField(unique=True)),
                ('nif', encrypted_model_fields.fields.EncryptedCharField(unique=True)),
                ('nis', models.CharField(max_length=20)),
                ('article_imposition', models.CharField(max_length=20)),
                ('commune', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('delai_moyen_livraison', models.PositiveIntegerField(default=7)),
                ('note_qualite', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('blackliste', 'Blacklisté'), ('en_validation', 'En Validation'), ('inactif', 'Inactif')], default='en_validation', max_length=20)),
                ('motif_blacklist', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs_crees', to=settings.AUTH_USER_MODEL)),
                ('domaines', models.ManyToManyField(to='suppliers.domaineactivite')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('reference_fournisseur', models.CharField(max_length=100)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant_ht_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('montant_tva_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('montant_ttc_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('montant_paye_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('validee', 'Validée'), ('payee_partiel', 'Payée Partiel'), ('payee_total', 'Payée Total'), ('litige', 'Litige')], default='recue', max_length=20)),
                ('fichier_facture', models.FileField(upload_to='achats/factures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.boncommande')),
                ('bon_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.bonreception')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('rc', 'Registre de Commerce'), ('nif', 'NIF'), ('assurance', 'Assurance'), ('agrement', 'Agrément'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='fournisseurs/documents/')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='DevisComparaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ht_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=4)),
                ('montant_ttc_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('delai_livraison_jours', models.PositiveIntegerField()),
                ('conditions_paiement', models.TextField()),
                ('fichier_devis', models.FileField(upload_to='achats/devis/')),
                ('est_retenu', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='suppliers.demandeachat')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='boncommande',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande', to='suppliers.demandeachat'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suppliers.fournisseur'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projet'),
        ),
    ]
