# Generated by Django 4.2.13 on 2026-05-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('designation', models.CharField(max_length=300)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('immatriculation', models.CharField(blank=True, max_length=20)),
                ('annee_fabrication', models.PositiveIntegerField()),
                ('annee_mise_en_service', models.PositiveIntegerField()),
                ('valeur_achat_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_amortissement_annuel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valeur_residuelle_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('taux_location_journalier_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_affectation', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('en_service', 'En Service'), ('en_maintenance', 'En Maintenance'), ('hs', 'Hors Service'), ('loue', 'Loué'), ('vendu', 'Vendu'), ('au_depot', 'Au Dépôt')], default='au_depot', max_length=20)),
                ('compteur_heures', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compteur_km', models.PositiveIntegerField(default=0)),
                ('prochain_ct_date', models.DateField(blank=True, null=True)),
                ('expiration_assurance', models.DateField(blank=True, null=True)),
                ('consommation_moyenne_lh', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fleet/photos/')),
                ('carte_grise', models.FileField(blank=True, null=True, upload_to='fleet/docs/')),
                ('police_assurance', models.FileField(blank=True, null=True, upload_to='fleet/docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('controle_technique', 'Contrôle Technique'), ('revision_generale', 'Révision Générale')], max_length=20)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('compteur_heures_entree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_panne', models.TextField(blank=True)),
                ('travaux_effectues', models.TextField()),
                ('prestataire_externe', models.CharField(blank=True, max_length=200)),
                ('cout_main_oeuvre_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_pieces_dzd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_total_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('prochaine_maintenance_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prochaine_maintenance_date', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fleet.engin')),
                ('mecanicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employe')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('consommation_ref_lh', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('reference_piece', models.CharField(blank=True, max_length=100)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=8)),
                ('prix_unitaire_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='fleet.maintenance')),
            ],
        ),
        migrations.AddField(
            model_name='engin',
            name='type_engin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fleet.typeengin'),
        ),
        migrations.CreateModel(
            name='BonCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('type_carburant', models.CharField(choices=[('gasoil', 'Gasoil'), ('essence', 'Essence'), ('gpl', 'GPL')], max_length=20)),
                ('quantite_litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_litre_dzd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('montant_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('station_service', models.CharField(max_length=200)),
                ('compteur_heures', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carburants', to='fleet.engin')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_journalier_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_total_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fleet.engin')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
        ),
    ]
