# Generated by Django 4.2.13 on 2026-05-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projet_taux_penalite_retard'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationengin',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_engins', to='projects.projet'),
        ),
    ]
