# Generated by Django 4.2.13 on 2026-05-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_arabe', models.CharField(blank=True, max_length=200)),
                ('date_naissance', models.DateField()),
                ('commune_naissance', models.CharField(max_length=100)),
                ('cni', encrypted_model_fields.fields.EncryptedCharField(unique=True)),
                ('num_cnas', encrypted_model_fields.fields.EncryptedCharField()),
                ('nif_fiscal', encrypted_model_fields.fields.EncryptedCharField()),
                ('adresse', encrypted_model_fields.fields.EncryptedTextField()),
                ('telephone', encrypted_model_fields.fields.EncryptedCharField()),
                ('rib_bancaire', encrypted_model_fields.fields.EncryptedCharField()),
                ('email_pro', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('situation_familiale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20)),
                ('nb_enfants', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/%Y/%m/')),
                ('contact_urgence_nom', encrypted_model_fields.fields.EncryptedCharField()),
                ('contact_urgence_tel', encrypted_model_fields.fields.EncryptedCharField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Interim', 'Intérim'), ('Stage', 'Stage'), ('Apprentissage', 'Apprentissage')], max_length=20)),
                ('date_embauche', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire_base_crypt', encrypted_model_fields.fields.EncryptedCharField()),
                ('mode_paiement', models.CharField(choices=[('virement_cpa', 'Virement CPA'), ('virement_bea', 'Virement BEA'), ('virement_bna', 'Virement BNA'), ('cheque', 'Chèque'), ('especes', 'Espèces')], max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En Congé'), ('suspendu', 'Suspendu'), ('demissionne', 'Démissionné'), ('licencie', 'Licencié'), ('retraite', 'Retraité')], default='actif', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Technicien', 'Technicien'), ('Maitrise', 'Agent de Maîtrise'), ('Cadre', 'Cadre'), ('Cadre_sup', 'Cadre Supérieur')], max_length=50)),
                ('coefficient', models.PositiveIntegerField()),
                ('salaire_base_min', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salaire_base_max', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('mission', 'Mission'), ('conge', 'Congé')], default='present', max_length=20)),
                ('heures_sup', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('note', models.TextField(blank=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='employees.employe')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projet')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees.poste'),
        ),
        migrations.AddField(
            model_name='employe',
            name='wilaya_naissance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employes_nes', to='accounts.wilaya'),
        ),
        migrations.AddField(
            model_name='employe',
            name='wilaya_travail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employes_wilaya', to='accounts.wilaya'),
        ),
        migrations.CreateModel(
            name='DocumentEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('cni', 'CNI'), ('cnas', 'Carte CNAS'), ('diplome', 'Diplôme'), ('casier', 'Casier Judiciaire'), ('residence', 'Certificat de Résidence'), ('contrat', 'Contrat de Travail'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='employees/documents/%Y/%m/')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Interim', 'Intérim'), ('Stage', 'Stage'), ('Apprentissage', 'Apprentissage')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire_base_dzd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='employees/contrats/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='employees.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Annuel'), ('maladie', 'Maladie'), ('maternite', 'Maternité'), ('paternite', 'Paternité'), ('exceptionnel', 'Exceptionnel'), ('cacobatph', 'CACOBATPH (BTP)'), ('sans_solde', 'Sans Solde')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_jours', models.PositiveIntegerField(default=0)),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='employees/conges/%Y/%m/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employees.employe')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('indemnite_zone', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prime_rendement', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('heures_sup_montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('indemnite_repas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prime_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('autres_primes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cnas_salariale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('irg', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retenues_diverses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='employees/bulletins/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bulletins', to='employees.employe')),
            ],
        ),
    ]
