# Generated by Django 4.2.13 on 2026-05-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employe_projet_affecte_employe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='cacobatph_salariale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
